# Generated by Django 4.2.3 on 2023-10-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
