# Generated by Django 4.2.3 on 2023-10-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_address_alter_product_quantity_order_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="building_name",
            field=models.TextField(default=""),
        ),
    ]
